### ISSUE TITLE
Compile static lib as a fat binary 

### ISSUE THREAD

**Issue by schell** [ExactTarget/JB4A-SDK-iOS#7]
Hi there! It would be great if we could still compile our apps without having to resort to conditional linking. Is this at all possible? Right now conditional linking requires the newest cocoapods which causes some other problems with other libraries.

**Comment by jsylviaSF** [comment]
The library is compiled as a "Fat" binary and can be used on all platforms including the simulator.

**Comment by schell** [comment]
My bad! It looks like some other bugs and some tricky documentation lead me to believe this was the case - thanks!
